# standard jekyll configuration

permalink: date
pygments: true
markdown: rdiscount
baseurl: /

source: .
destination: ./_site
plugins: ./_plugins

# configuration required for some pages

domain: robinh00d.cn
title: robinh00d的网络日志
author: robinh00d
email: robinh00d@sina.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
   username: kernelhack

disqus:
   id: kernelhack
